spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: Jishan@Verso

server:
  port: 8002

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# it indicates that register with the below Eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/